name: NightVisionGoggles
version: '${project.version}'
main: com.ashkiano.nightvisiongoggles.NightVisionGoggles
api-version: '1.20'
authors: [ AshKiano, BitByLogic ]
commands:
  nightvisiongoggles:
    aliases: [ "nvg" ]
    description: Give the player a pair of goggles, or reload the config!