name: NightVisionGoggles
version: '1.8'
main: com.ashkiano.nightvisiongoggles.NightVisionGoggles
api-version: '1.16'
authors: [AshKiano]
commands:
  nightvisiongoggles:
    description: Gives the player a pair of night vision goggles